export type Story = {
  id: string;
  slug: string;
  title: string;
  description: string;
  summary: string;
  accent: string;
  /** Idioma del texto, si no es español. */
  lang?: string;
  /** Indicación que acompaña al título (p. ej. una canción para leerlo). */
  epigraph?: string;
  date?: string;
  content: string[];
  note?: string;
};

export const stories: Story[] = [
  {
    id: "1",
    slug: "aquel-prado-en-el-que-vivimos",
    title: "Aquel prado en el que vivimos",
    summary: "Un hombre que ya no recuerda su infancia recibe la visita de una sombra que pinta de azul sus memorias.",
    description:
      "Un cigarro robado, un árbol sin hojas y una flor blanca en un prado de verano. Años después, en la ciudad, una sombra empieza a visitarlo con cuadros de su vida y un pincel empapado en el color del cielo.",
    accent: "var(--accent)",
    content: [
      "Últimamente he intentado recordar.",
      "Dejo que olas de nostalgia golpeen mi árida memoria, esperando que empapen mi mente de recuerdos con los que tan solo puedo soñar en hundirme. Interminables noches en vela en las que me mantengo a la distancia, observando pensamientos que fueron míos, rogando ser absorbido por ellos, pero ya no son lo que eran, no son lo que sentí, son espejismos de una vida que ya no me pertenece. En tiempos muertos cierro los ojos y me dejo naufragar en el mar de memorias en el que tanto ansío ahogarme. El tiempo es tranquilo, la brisa agradable y, en consecuencia, sufro al saber que mi sueño nunca se hará realidad. Soy un náufrago surcando un océano en armonía, rezando para que en algún fugaz momento el agua salpique mi deshumedecida cara de marinero y por fin volver a sentirme capitán en tiempos de tormenta.",
      "Los días pasan a la velocidad de las horas y yo, perdido en un mundo que no llego a comprender, me limito a contemplar el jardín de memorias en el que en mi infancia solía perderme. Los tristes pétalos, cansados de esperar a que vuelva, se secan, obligándome a olvidar lo que una vez fui. Pero entre muerte y sequía hay una flor que, contra todo pronóstico, no se drena, un recuerdo que todavía irradia su joven inocencia. Un recuerdo por el que vivir.",
      "Recuerdo el ardiente sol del verano iluminando el vasto horizonte, fulgores cálidos envolviendo el bello mundo al que llegué a pertenecer. Ninguna nube oscurecía el luminoso espectáculo que el cielo ofrecía aquel día y el viento, para compensar la sequía del mes de julio, mecía tiernamente el campo a mi alrededor. Aquella tarde, mientras mi abuelo celebraba su cumpleaños, logré robar de la mesa de los adultos un solo cigarro junto a un mechero y fui en bicicleta al prado en el que una vez logré domarla. Fue a la edad de diecisiete años, cuando me senté en la amarillenta y marchita hierba del campo donde una vez viví mi infancia, y apoyé la espalda en el único árbol del paisaje. No brotaba hoja alguna de él.",
      "Aquella tarde decidí apoyarme en un cadáver, y por alguna razón es el recuerdo más cálido que tengo.",
      "Durante horas fui una extensión de aquellas ramas sin vida, contemplando serenamente el cigarro, elevándolo en el aire, obligándome a perder la vista en aquel limpio cielo que siempre vestía de azul. A lo largo de esa tarde no pude pensar en nada más que en aquel sencillo color. ¿Cómo era posible que miles de personas amaran un color tan común? ¿Qué tiene de especial querer lo que todos tienen? Todo el mundo, incluyendo mi familia, se enamoró de algo que nunca me llegó a cautivar. Pregunté a quien pudiese para llegar a comprender la hipnótica realidad a la que todos pertenecían. ¿Qué es lo que veis, por qué os enamoráis de algo que no os puede ver? Nadie respondía a lo que yo creía una fácil pregunta, no se creían que no sintiera lo que ellos, no se imaginaban una vida sin el azul del cielo.",
      "Con el tiempo, el verano fue muriendo y con él mi curiosidad. Llegó el último atardecer antes del otoño y, entre los finales rayos de sol, escuché la única respuesta que jamás recibí. “Reconforta”, murmuró mi abuelo casi a sí mismo mientras contemplaba el desnudo horizonte que se extinguía frente a nosotros, ambos sentados en sillas de madera en el corazón del extenso prado. Recuerdo mirarle tras su simple respuesta, confuso, y tan solo ser respondido por el avioletado color del anochecer reflejado en sus apagados ojos. Tras largas horas el silencio gobernó el campo, acompañado con la serena presencia del viento. Decidí levantarme lentamente, tratando de no despertar a mi querido anciano, pero fui sorprendido por su tranquila voz: “Hazme un favor”, recitó mientras descansaba con los ojos cerrados. “Busca en mi habitación un pequeño libro, tráemelo cuando lo encuentres”.",
      "Bajo su almohada encontré una colección de fotos.",
      "Me dio las gracias con su risueña mirada y se despidió de mí con un leve movimiento de manos. Al marcharme pude ver cómo aquel hombre miraba tiernamente el libro, pero incluso desde la distancia vi cómo su mirada se teñía con tristes pensamientos que nunca llegué a descifrar. En esa última madrugada de verano, mi abuelo nunca abrió el libro. Tan solo lo abrazó, como una buena madre a su aterrado hijo, y decidió observar el solitario camino por el que todos llegamos meses atrás.",
      "—oo0oo—",
      "Di la primera calada de mi vida contemplando la hierba muerta del suelo. El seco humo del cigarro inundó mis desprevenidos pulmones y no pude hacer otra cosa que toser, regando lo marchito con mi amarga saliva. Sonreí, esclavo de mi nuevo vicio, inconsciente de que aquel día el cielo cambió de color. En cuestión de minutos, el tan amado azul, que tantas preguntas me causó, fue asfixiado por una profunda oscuridad. Gruesas nubes dominaban el firmamento, engendrando una noche artificial. Huecos asimétricos entre ellas permitían que los ardientes calores del sol siguieran iluminando el paisaje. Una imagen grabada a tinta en mí: pequeños hilos de luz atravesando las colosales montañas de nubes, peleando por iluminar la inmensa penumbra que fue cimentada al fumar. La lluvia pronto se volvió parte del trágico escenario y, por tanto, decidí marcharme. Me levanté cuidadosamente, tratando de no dañar al viejo árbol, pensando que con suerte mi compañía le había inspirado a permitir que nuevas hojas crecieran sobre él. Una vez de pie noté un cercano haz de luz. Mi curiosidad me obligó a visitarlo y, al acercarme, no pude hacer mucho más que sonreír. A mis pies, una flor blanca de débiles pétalos cuyos contornos estaban firmados por pequeñas ondulaciones doradas. La veía bailar sutilmente por el impacto de las gotas de lluvia, como una bailarina confusa al no recordar su próximo paso al actuar.",
      "Fumé mi última calada contemplando el glorioso espectáculo de luces que aún alumbra mis noches en desvelo. Bajé la cabeza, me agaché y apoyé el resto del cigarrillo al pie de la única flor que rebosaba de joven vida en aquel pastizal, pensando que la lluvia lo apagaría. Esa tarde, al irme, no miré atrás. Tras cada paso que daba, las nubes oscurecían mi mundo, y fue entre la penumbra del paisaje y el crujido de mis pasos al marchar, que vi con el rabillo del ojo cómo la única flor que pudo llegar a ser, seguía brillando en la oscuridad.",
      "—oo0oo—",
      "El mundo palideció una vez abandoné el prado en el que ya nada brilla, el campo que se perdió entre las nubes. Desde aquel día, ningún color logró despertar nuevas obsesiones; ninguna luz me guió a ninguna flor. Me convertí en prisionero de monótonas calles en las que todos viven en silencio, asustados de despertarse de la soledad en la que mueren. Es un triste mundo de enfermos y yo, con el cigarro en los labios, tuve la suerte de encontrar la cura.",
      "Hace apenas unos meses salí de mi apartamento con la esperanza de poder encontrar la salida de este lugar. Agarré el paquete de tabaco junto al mechero y caminé sin rumbo alguno por las laberínticas calles de las que todos quieren escapar, fijándome en los altos edificios grises donde crecen los niños, compadeciéndome de ellos por tan solo poder jugar en frías escaleras de metal. Pasé un pequeño rato mirando las grandes estructuras de hormigón que formaban la metrópolis en la que fumaba, pero pronto comenzó a llover. Tiré el cigarrillo sin prisa alguna y caminé de vuelta a casa, reflexionando sobre el vicio que me obligó a empaparme en aquel remoto rincón de la ciudad. ¿Por qué me dejaba matar? No entendía cómo seguía siendo adicto a aquellos insípidos cigarros si no me daban la libertad de hace tantos años atrás.",
      "Mientras reflexionaba, fui brevemente distraído por una pequeña familia. Vi desde la distancia cómo una madre intentaba resguardar a su hijo de la fría lluvia, caminando de portal en portal, agarrando a su niño de la mano, pero aquel pequeño se detenía de vez en cuando en medio de la solitaria calle, soltando a su mamá para poder observar con atención el cálido color que irradiaban las farolas. El niño se empapaba mientras miraba con inquietud lo que un día le dejaría de parecer interesante. Juraría que en aquel momento vi brillar la farola un poco más, tratando de arropar a su único admirador del frío que le rodeaba. La madre se acercó a su hijo y él, sin perder la vista de su nueva obsesión, alzó su brazo para poder agarrar de la mano a su madre. Se marcharon tan rápido como llegaron y, una vez se fueron, las farolas irradiaban con menos fuerza. No tenían razón alguna para brillar, ya nadie las volvería a mirar. Aquel día, por muy pocos segundos, pude ver lo que pocos llegan a contemplar: la ilusión de lo ordinario al ser descubierto una vez más.",
      "Finalmente llegué a mi portal. El frío había penetrado mi ropa, forzando una desagradable sensación en mi piel. Subí hacia mi piso tiritando y, una vez frente a mi puerta, me di cuenta de que estaba abierta. Al entrar lentamente a mi casa vi a un hombre, una silueta situada frente a la única ventana de mi pequeño apartamento. Cualquiera habría sentido pavor al ver una sombra que no era la suya, pero por alguna razón yo sentí paz. El extraño sostenía un pequeño lienzo en su mano que estaba tapado parcialmente por el largo abrigo que llevaba, impidiéndome ver lo que el hombre había pintado. La sombra me miró con ojos vacíos y, con su voz tranquila, me pidió que me sentara. Tomé asiento en una pequeña silla mientras él se sentaba enfrente mío en el sillón.",
      "Él me miró sin pronunciar palabra, aunque sus ojos hablaban idiomas que cualquiera podría comprender. Había una profunda tristeza acompañada de rastros de cansancio en su dialecto. Tras largos segundos de calma, empezó a desvelar lentamente el lienzo.",
      "Lo que vi aquella tarde pausó mi mundo.",
      "La imagen de vivos colores que mostró aquel hombre era del campo que creí nunca volvería a brillar. Su arte era una memoria perdida y, al verlo, sentí una sensación de calor que tan sólo unos brazos pueden dar. Sentí cómo el frío y la humedad acumulada abandonaba mi cuerpo, dejando una agradable sensación de tranquilidad en mi corazón. Seguí mirando la ilustración con increíble entusiasmo, conmocionado por poder volver a ver lo que había perdido hacía tanto tiempo atrás. Pero entre mis lágrimas y sonrisas aquella impasible sombra me observaba con dolor. Le miré a los ojos, confundido, mientras sacaba de un pequeño bolsillo su pincel. No entendía lo que estaba pasando pero él procuró responder sin palabras. De su gran abrigo sacó un pequeño bote de pintura. Un color oscuro, parecido a la profundidad del océano. Empezó a mojar delicadamente el pincel en ese gran amado color. Mi confusión se convirtió en terror. No podía creer que estuviera a punto de perder lo que nunca logré recuperar. Le supliqué desde lo más profundo de mi alma que se detuviera, que no hiciera lo que estaba a punto de hacer. “Déjame quedármelo, por favor”, sollocé con toda la fuerza que mi cuerpo asustado pudo reunir. “¿Por qué quieres recordar?\", respondió con su sonámbula voz. \"Necesito algo por lo que vivir\", dije llorando, suplicando a su alma para que me permitiera recordar quién fui. El hombre dejó de remover la pintura con su pincel. Me miró y comenzó a preguntarme sobre los detalles del recuerdo que tenía en sus manos, pero yo no pude responder a ninguna pregunta. La memoria, aunque mía, era distante. El tiempo había pasado y los detalles eran inexistentes. Por cada pregunta sin respuesta, el hombre pintaba una línea azul, gruesa y opaca, que cubría cualquier color que le precediera. La intensidad del recuerdo se desvaneció en un azul que borraba cualquier emoción o relieve de lo que había llegado a vivir. A última hora de la tarde, cuando la fría luz del crepúsculo entró por la ventana, el cuadro acabó siendo de un solo color y volví a ser dueño de tan solo un recuerdo.",
      "El hombre siguió viniendo, cada vez presentando recuerdos que yo mataría por volver a vivir. En cada visita me mostraba cuadros resumiendo mi vida, pero cada vez que me preguntaba, volvía a sufrir la puñalada del pincel. Un día, el hombre dibujó a una joven. \"¿La conocías?\" me preguntó con su pausada voz. Al ver el dibujo, mi alma se llenó de alegría ¡Sí, me acordaba de ella! Le conté todo, cada ínfimo detalle que nadie más que yo podía saber. Tenía que demostrar que la recordaba, quería demostrar que ella seguía importando después de todos estos años; no fue elección mía olvidarla, simplemente sucedió. Luché por su recuerdo, hablé durante minutos con tal de salvarla del olvido, pero tras todo lo que dije se limitó a preguntar con suavidad: \"¿Cuál era su color favorito?\" Sentí un profundo peso en el pecho, casi como si me hubieran hundido el corazón. Pensaba que podría defender su memoria, pero por una pregunta que no hice, ahora hay una persona menos a la que puedo recordar. \"No lo sé\", respondí, y el hombre, con visible tristeza, empezó a pintar el lienzo una vez más.",
      "Con el tiempo, las visitas se hicieron menos frecuentes; cada vez había menos recuerdos por los que luchar. Uno de los últimos días que vino, me enseñó un cuadro. Me preguntó sobre él, pero no quise contestar.",
      "\"Nunca quise olvidar todo esto\", le dije.",
      "Él me contestó:",
      "“Sé que no quisiste olvidar, nadie suele hacerlo. Pero el tiempo lo cura todo, incluso lo que no necesita sanar. La manera en la que miras los cuadros te delata. Sé que aprecias todo lo que una vez te pasó y que ansías poder volver a agarrar de la mano aquellos extraños sentimientos que ya no reconoces. Pero tienes que entender que lo que te ha ocurrido no es coincidencia. Decidiste dejar el campo, tu familia. No desde la maldad, sino desde la ilusión de tu joven corazón. Querías prosperar y viajar, poder vivir la vida que tanto ansiabas. Empacaste la maleta con esperanza, pero ¿quién diría que te olvidaste de llevar lo que más necesitarías? No recuerdas porque no hay nada que te devuelva el recuerdo; no trajiste nada que te ayudara a mirar atrás. En aquella casa en el prado, la que he pintado cientos de veces, cada esquina rebosaba de memorias. El presente y el pasado se mezclaban entre sí, haciendo difícil olvidar cualquier pequeña historia. Pensabas que siempre sería así. Pero ahora que vives en un lienzo en blanco, nada te devuelve lo que perdiste, nada se asemeja al color de tu hogar. Todo es nuevo, pero eso no es malo. Aun siendo joven, puedes aprender de lo que te ha pasado. Tuviste un gran fallo en tu anterior vida: nunca llegaste a preguntar. Las personas desaparecen de tu mente; no sabes quiénes eran aquellos que te arropaban. Una madre, un padre, incluso un abuelo. Sabías que eran tu familia, pero nunca quisiste aprender más. Te quedaste en lo superficial. Nunca preguntaste por su comida favorita, aunque ellos sí; ellos sabían todo de ti mientras que tú no sabes nada de las melodías que les hacían bailar ni de los libros que les hicieron llorar. Al nunca preguntar nada mundano, nada de la vida cotidiana puede traerte al pasado. Si hubieras preguntado por armonías, te acordarías de tu abuelo cada vez que escuchas una canción; le encantaban. De comida, recordarías el amor de tu madre por cocinar, y de poemas, a tu padre al leer cualquier libro sobre la Segunda Guerra Mundial. La única vez en la que decidiste preguntar fue por ese color que tú creías que era tan amado. Pero lo hiciste demasiado tarde; ya había preguntado yo”.",
      "Se levantó de camino a la puerta:",
      "“Ya no tengo más memorias por las que preguntarte, tampoco cuadros que quitarte. No me agrada saber que has perdido todo lo que tanto amaste, pero no hiciste mucho para evitarme. Nadie suele hacerlo”.",
      "Tras su despedida, la sombra del olvido se marchó, obligándome a reflexionar sobre todo lo que dijo en aquella primera tarde de primavera. Nunca comprendí quién era aquella sombra azul, pero es por él por lo que ahora entiendo a mi familia. Ellos no amaban el azul, simplemente lo aceptaron como parte de su vida. Todos perdieron su batalla ante el vasto color del cielo. “Reconforta”, dijo mi abuelo, refiriéndose a su derrota. Ya no tenía por qué pelear contra el olvido. Decidió olvidar, pues se cansó de defender sus memorias. Mi familia se rindió y lo que yo creía su color favorito era la bandera de su triste fracaso ante aquella sombra. Me duele saber que perdieron ante el olvido, y es por eso por lo que no pienso ceder ninguna nueva victoria. Pelearé por mis nuevas memorias pues ahora entiendo que si tras una larga vida tan solo nos queda el recuerdo, hay que hacer que este sea fácil de encontrar. Es por eso por lo que aquel joven nunca olvidará la tarde en la que observó las farolas mientras llovía, pues siempre las podrá ver desde la ventana de su hogar, y por lo que yo nunca dejaré de fumar.",
      "Después de todos estos meses viendo desaparecer mis recuerdos, di por hecho que cualquier momento que hubiera vivido antes de mi treinta cumpleaños, el día en que conocí al hombre de azul, se había perdido para siempre en un eterno lienzo del color del cielo. Pero por alguna razón que no comprendo estaba equivocado, te estoy empezando a recordar. Veo cabellos rubios meciéndose en el campo donde una vez crecí. No sé qué es lo que veo, no sé quién eres, pero sé que hubo una vez en la que lo fuiste todo para mí. Tu sonrisa, tu rostro, cada vez se está volviendo más presente. Debería alegrarme por poder recordarte, pero tengo miedo de volver a perderte. Nunca te pregunté por tu color favorito y, por alguna razón, eres todo lo que queda de lo que fui. En tiempos muertos, cierro los ojos y tu memoria estalla en mi mente, la adrenalina recorre mis venas y corro por toda mi casa atemorizado con la idea de olvidarte y darle una razón al hombre de azul para volver. Acelerado, busco algo con lo que asociarte, pero no hay nada que sea tan valioso como para que me recuerde a ti, por eso he decidido guardarte en el único lugar que sé que nunca perderá importancia, un lugar que nunca se alejará de mí. Hace tiempo me pregunté por mi adicción al tabaco. Nunca supe por qué no podía dejarlo y es ahora cuando entiendo que soy adicto a una vida pasada y es tras cada calada cuando soy devuelto a ella. He decidido refugiarte en mi mente, en el único recuerdo que no se desvanecerá. Siempre te recordaré como la flor que ardió al contacto de mi primer cigarro, siempre te recordaré mientras me esté dispuesto a matar. Te prometo que te buscaré en esta nueva vida y, si la suerte me sonríe, te podré volver a encontrar. De momento estoy aprendiendo a dibujar para esta nueva aventura; no me permitiré olvidar nada de lo que me ocurra. Al verte, si me recuerdas, podrás ver cuánto he cambiado desde que fuimos niños, y te prometo dibujar con el que tú nombrarás tu color favorito. Te recordaré por lo que te mueva el alma y tú me recordarás por mis dibujos, mi arte. El futuro es emocionante, estoy dispuesto a empezar esta nueva etapa de mi vida, pero aún no sé dónde encontrarte y es por eso por lo que me limito a perfeccionar mis dibujos mientras fumo, para asegurarme de poder tener algo con lo que recordar. Tan solo tengo una cosa clara: seguiré fumando, lo haré hasta que nos volvamos a abrazar. Para que tú y yo, de una forma u otra, sea en mi memoria o en el presente, podamos volver a vernos en aquel olvidado prado en el que crecimos de la mano hace tanto tiempo atrás.",
    ],
  },
  {
    id: "2",
    slug: "arenas-sin-playa",
    title: "Arenas sin playa",
    summary: "Sentado en una orilla que se oscurece, alguien se deja cubrir por la arena mientras recuerda unos ojos negros.",
    description:
      "La playa se apaga bajo un cielo que se cierra y la arena empieza a cubrirlo. En la negrura del paisaje reaparecen unos ojos en los que una parte de él se perdió para siempre.",
    accent: "var(--accent-mid)",
    content: [
      "No sé hace cuánto tiempo me perdí. Sentado en la orilla, a pocos metros del mar, veo el horizonte ser acechado por un primitivo dolor que vence eternamente al olvido. Noto su extraño espesor residiendo por las nubes, deslizándose por sus expuestas pieles. Corrompiéndolas. Prohibiendo ningún frágil hueco de existir entre ellas. El blanco cielo que antes florecía se ha convertido en una brusca y apenada pincelada negra que consume la esencia de lo que fue. El opaco firmamento roza el nivel del mar y los astros se han vuelto inmateriales. Puedo sentir en mi pecho la nueva creación que el cielo está engendrando. Algo incomprensible está a punto de ser expuesto ante mis ojos. Una esencia codificada, indiferente a mí, la cual me fuerza a decidir entre la uniformidad de la penumbra o la inquietante eminencia de la creación. El viento arrastra la carbonizada arena del paisaje sobre mi piel, se amontona lentamente sobre mi cuerpo, tapándome, tratando de hundirme en su fría esencia. La playa se ha cansado de mí. No me desea en su nuevo mundo. La tristeza de no ser elegido desemboca en mi aceptación. Decido seguir observando lo que me rodea. Oigo el sonajero de la calma deslizarse por la gravilla. Se asemeja al latido de un arrítmico reloj. Pienso en el limitado tiempo que me queda en esta playa en vías de extinción. La arena me sigue consumiendo, pero no me muevo, no tengo prisa en huir de mi trono de carbón. Contemplo la extinguida luz del día adentrarse en el océano, perdiéndose entre la acenizada marea, para jamás volver. El agua viste del único color que embruja mi agraviada alma. Las olas, al rascar contra las rocas, simulan el cantar de las sirenas que nunca vi. Me siento cansado.",
      "La negrura del paisaje provoca en mí el recuerdo de sus eclipsados ojos de mármol. Me pregunto qué será de ella. Llegué a contemplar diamantes a los que nombraron pupilas; distinguí en su eterna noche la promesa del día. El paisaje me recuerda a su nombre. Puede que por eso me sienta tan tranquilo al dejarme ser sumergido por la arena oscura; volver a fundirme en sus negros ojos. Permitir que mi alma pierda el peso que carga, ser sumergido en su mirada y reencontrarme con la galaxia de su iris. Volver a ser aquel astronauta que se perdió en sus nebulosos ojos. Visitar secretos en forma de planetas, presenciar atardeceres de otros mundos. Me regaló un universo el cual parte de mí nunca quiso abandonar. Un fragmento de mí se separó para explorar su fantasía. Esa esencia mía cortó comunicación conmigo mismo para perderse en ese más allá. Parte de mí se convirtió en un vagabundo en sus ojos de cristal.",
      "Desde hoy, la playa en la que solía contemplar a las estrellas con la esperanza de encontrarme está nublada. El horizonte ya no brilla como solía; cuenta la historia de mi amarga verdad. Mirar al cielo todas las noches, soñando ver mi reflejo en los astros, para finalmente poderme recuperar. Pero hay veces en las que me despierto pensando, ¿y si soy yo el astronauta que nunca quiso regresar? ¿Si esta playa es su mundo, y ella me está empezando a olvidar? No sé si soy yo mismo, o lo que nunca pude salvar. La arena ha parado de consumirme. El viento sopla la melodía de la soledad. La marea asciende, roza mis pies: me está incitando a nadar. Mañana cuando despierte me habré marchado de la arena. No quiero ver el nuevo mundo que se está por formar. Aunque no sé si volveré a casa, mirando a la arena o nadando por ese mar.",
    ],
  },
  {
    id: "3",
    slug: "algas",
    title: "Algas",
    summary: "Un poema sobre una niña que el mar no quiere devolver.",
    description:
      "Pelo y ropa mecidos por la marea, una niña que decidió jugar y una guerra silenciosa entre la orilla y el océano por guardar su recuerdo.",
    accent: "var(--accent)",
    content: [
      "Pelo que fue liso está siendo mecido por la marea.\nSe extiende como grietas por el frío ámbito en el que flota.\nAgua gris reflejando el color del cielo:\nun oscuro grisáceo, un humo de hoguera.",
      "Largas horas destiñeron su ropa\nSu joven piel, agrietada por la sal.\nEn la lejanía rugen las olas; lloran.\nA sus actos: consecuencias que nadie pudo imaginar.",
      "Sus piernas son sumergidas en un negro abismo.\nOjos rojos, aunque muertos, observan lo más profundo del mar.\nElla tan solo una cría, la cual sonriendo, decidió jugar.",
      "Pelo y ropa mecidos por las mareas, quieren guiarla de vuelta a su hogar.\nPero la corriente, avergonzada, ancla a la niña, no la quiere revelar.\nNo quiere que nadie la encuentre; que sus negros ojos, vuelvan a brillar.",
      "Entre orilla y océano; una guerra.\n(Todos quieren su recuerdo, todos la quieren cuidar.)",
    ],
  },
  {
    id: "4",
    slug: "el-limite-de-un-poeta",
    title: "El límite de un poeta",
    summary: "Un artista que dedicó su vida a retratar a alguien descubre que el límite nunca fue el lápiz.",
    description:
      "Lápices, tinta, fotografía, cristal y danza: ningún arte alcanza a describirla. Aplaudido por una obra que considera un fracaso, un poeta decide dedicarle lo único que nunca dejará de existir.",
    accent: "var(--accent-mid)",
    content: [
      "Siempre adoré la idea del lápiz más afilado, fue una obsesión que perduró en mi cabeza desde que aspiré a ser lo que soy. Me decía a mí mismo que con él lograría retratar con detalle lo indescriptible, que dibujar lo intangible sería tan fácil como inspirarme por tu voz. Pasé innumerables noches soñando, pensando que al fin podría dibujar cualquier ínfimo detalle sin error. Viví en una burbuja de esperanza hasta que conocí tus pestañas; fueron ellas las que rajaron mi pompa de ilusión. Algo tan simple como un par de líneas onduladas me atemorizaban, no se asemejaban a la realidad. Cualquier ruta hacia tus ojos era inconcebible, millares de trazos que, aunque simples, me hacían fallar. Pasé gran parte de mi vida enfocándome en minúsculos detalles y aun así no pude siquiera dibujar el pelo que siempre amé. Intenté tus ojos, pero nunca pude hacerlos tan profundos. Miles de lienzos y acuarelas destrozados, ninguno igualaba al tacto de tu piel. Comprendí que el límite era el lápiz, así que lo cambié. Traté de escribir con tinta azul una íntima balada, pero el diccionario carecía palabras, al igual que notas la escala musical. Intenté fotografiarte, pero cada imagen terminaba saturada por tu fulgor. Cualquier imagen tuya es ver una galaxia inundada de color. Esculpí en cristal tu ser, pero nunca encontré vidrio que se asemejara a tu pureza y creé cientos de coreografías que terminaron siendo una ofensa. No había movimiento humano que describiera tu belleza. Con el tiempo me di cuenta de que el límite de un poeta no es su lápiz, sino sus manos. Pues por mucha ilusión que mis ojos resplandezcan al verte, es mi pulso lo que dicta el resultado. Por miles de años los humanos construyeron ciudades del barro. No entiendo cómo no pude dibujarte con el lápiz que tanto me inspiró. No fueron faltas de ganas, fue falta de calidad. Soy un pésimo artista y nadie parece darse cuenta de mi mal. Tras toda una vida trabajando, me quedé en el intento, y los demás aplaudieron como si fuera la obra final. No se dieron cuenta de que le faltaba más a la historia. No saben que hay mucho más que contar. Viven en la ignorancia de mi arte y es un dolor que siempre me acompañará. Si el mundo entero estalló en aplausos con mi intento de describirte, no logro imaginar la reacción del universo al desvelarte sin fallar.",
      "Soy famoso por mi irreconocible derrota, un simple diccionario que creé para poder definirte; cientos de palabras que no existen, pero hacen falta para conocerte, palabras que grabaste en lo más profundo de mi memoria cada vez que te vi. No estoy orgulloso de reducirte a tan solo unas cuantas palabras inventadas, pero eso es todo lo que pude hacer por ti. Eres todo lo que no pude dibujar: la vigésima octava letra del abecedario, la no existente nota musical. Por ello, por mucho que el público lo ame, no puedo dedicarte el libro, no tendría sentido dedicarte la obra que nunca llegué a completar. Siempre me dolerá no haber podido crear un nuevo arte para ti, pero esa es mi cruz por cargar. No puedo firmarlo, no con orgullo, no soy el artista que todos admiran, soy un iluso, un fraude que nunca te puedo retratar. Por eso no volveré a crear, pues son todas las ideas que aún flotan en mi mente las que viven en su máximo esplendor, ya que viven en un lugar donde no hay intento de expresarlas a nadie más que yo. Te pido que confíes en mí, pues nunca volveré a declarar mis sentimientos, pero te prometo que si miras a lo más profundo de mis pupilas verás tu reflejo en colores que nunca llegaron a existir. Te dedicaré lo que nunca cesará de vivir, pues el papel se pudrirá con el tiempo y las palabras volarán por el viento. Te dedico lo que siempre existirá, mi pasión, mis ideas, mi amor hacia ti.",
      "El límite de un poeta fue conocerte.",
    ],
  },
  {
    id: "5",
    slug: "la-incertidumbre-del-calor",
    title: "La incertidumbre del calor",
    summary: "Un poema sobre un espejismo en el desierto.",
    description:
      "Entre la arena ardiente y la refracción del calor, una figura en la lejanía que parece acercarse y desaparecer, y una pregunta en la noche fría.",
    accent: "var(--accent)",
    content: [
      "Entre la sofocante calidez y el deslumbrante brillo del atardecer\nMientras la anaranjada arena me cortaba al ser mecida por el viento\nY mis pies se sepultaban en el suelo\nCreí verte a lo lejos, observando.",
      "Apenas con fuerza me arrastré por la arena\nDesterrando la gravilla de mis quemados pies\nY entre la refracción del calor\nY las sombras de las dunas\nCon mis ojos llorosos, me pareció verte ver",
      "Pero al dar un rendido paso,\nForzándome a sentir el ardor de las quemaduras\nQue ya había terminado de doler,\nTe miré en la lejanía\nEsperando verte cerca\nPero parecías desaparecer.",
      "Estaba cansado,\nMe tumbé en la arena\nYa no merecía la pena ascender",
      "Aquella noche, mientras el frío me acurrucaba\nY las estrellas brillaban, peleando por destacar.\nPensé en aquel espejismo, reflexionando para preguntar,",
      "Si no estás porque te alejas\nO porque nunca llegaste a estar.",
    ],
  },
  {
    id: "6",
    slug: "el-frio-del-filo",
    title: "El frío del filo",
    summary: "La Muerte, cansada de su oficio, ve nacer una flor de sus propias lágrimas.",
    description:
      "La Parca camina descalza por el prado en el que nació. De sus lágrimas brota una pequeña flor naranja que promete no tocar nunca, hasta que el Invierno le susurra que vendrá a por ella.",
    accent: "var(--accent)",
    content: [
      "La Muerte caminaba descalza por el azul prado en el que nació. Sin prisa, avanzaba por el denso pastizal de su infancia, el cual, con inmensa belleza, era sumergido bajo un fresco resplandor. Era la luna, compañera de la niñez, la que iluminaba la noche, dándole la bienvenida a la amiga que siempre adoró. La Muerte vagaba lentamente por el recuerdo de su hogar; tristes lágrimas inundaban sus ojos, finalmente comprendía que nadie podía ser guiado por su mano al único lugar en el que pudo sentir paz. El viento trató de consolarla soplando una gentil brisa, meciendo tiernamente el prado, intentando apartar con ternura su salado dolor. Ella no merecía ahogarse en pena. En el campo, todos conocían a La Parca y su buen corazón.",
      "Aquella noche, con apenados ojos, observó el sutil brillar de las estrellas y confesó a la noche que, por error, prohibió a quien no debía admirar el cielo que siempre amó. Esa tarde, antes de llorar, la Parca visitó una pequeña casa en el monte. Ella nunca quiso utilizar su guadaña al trabajar; sabía que era un método cruel con el que despedirse de la vida. Prefería desarropar con sutileza al desgraciado y llevarlo en brazos a su nuevo hogar, un lugar en el que, aunque perfecto, nadie quería ir por miedo a olvidar. Esa noche, al abrazar a un dulce anciano que hablaba en sueños, dejó su estéril arma en el suelo, sin saber de un pequeño nieto cuyo interés se apoderó de él. Cuando volvió a la casa para coger su herramienta, había un tierno y frío cuerpo agarrando sin fuerza el instrumento, esperando ser llevado de vuelta con su abuelo, para que este le contara historias de la vida que nunca pudo tener.",
      "Mirando a la luna, la Muerte preguntó si su trabajo hacía algún bien. Sollozó desconsoladamente, dejando que sus ácidas lágrimas regaran el seco barro, rezando que de él naciera el pequeño niño al que impidió crecer. Durmió rodeada de verde hierba y, en sus sueños, un espejismo la abrazó; le dijo que todo iría bien. La Parca amaneció rodeada de pasto muerto; su amiga, la luna, se fue. El universo disfrutaba al recordarle la maldición de su ser. Se levantó sumergida en impotencia, miró a la pálida hierba y, en ese instante, juró al viento que nadie la volvería a ver. Se iría lejos; nunca más haría daño a nadie, nada más sufriría por su piel.",
      "Empezó a caminar, convencida de que nunca volvería. Pero, entre amargos pasos y espesa tristeza, el viento sopló con fuerza, obligándola a mirar al prado en el que aprendió a soñar. Y fue ahí cuando la Muerte vio que, de sus lágrimas, una pequeña flor naranja comenzaba a brotar. Emocionada, quiso acercarse a ella, arrodillarse y acariciarla, y darle la bienvenida al mundo en el que el sol la iluminaría hasta más no poder. Pero, antes de rozarla, recordó la maldición de su tacto y, desde la distancia, observó con entusiasmo aquella planta, prometiéndole que nunca la haría doler.",
      "Los meses pasaron despacio y, de esa joven flor, el campo no paró de crecer. La pradera, que siempre fue verde, fue raptada de su esencia. Ahora era inundada de colores que brillaban incluso en el más oscuro anochecer. La Muerte, aterrada de dañar las plantas, cada vez que nuevas brotaban daba un paso atrás; era feliz en la distancia, sabiendo que, por fin, algo suyo no arrebataba a nadie placer. Al pasar la mitad del año, decidió irse del campo; su hogar no era suyo, era de lo que nunca dejaría de querer.",
      "Se fue lejos, exploró el mundo y nunca logró encontrar una flor como la que crió. Ella era feliz, investigando, olvidando el trabajo que, aunque suyo, nunca quiso hacer. Vio por primera vez cómo la gente vivía. Sonreían. Nadie tenía el miedo que ella estaba acostumbrada a ver. Decidió que su ausencia era razón de alegría y, por tanto, se alejó de la multitud. Pasaron largas semanas en las que se alejó de todo. Y, tras cientos de kilómetros, finalmente se sentó en la orilla de una desconocida playa para descansar. Sonrió al mirar al océano, recordando cómo sus saladas lágrimas crearon el milagro que su tacto nunca pudo lograr. Contempló el horizonte por horas; perdió su mirada en la distancia, dejándose mecer por el hablar del mar. Cansada, cerró los ojos y volvió a soñar. Se dejó guiar por su mente, pero, mientras no miraba, su ropa se volvió más fría; las olas cesaron de avanzar. Fue entonces cuando observó cómo una negra tormenta se empezó a formar. La Muerte se levantó sin perder de vista al horizonte y, en ese instante, un gélido susurro se hizo nombrar.",
      "—Vendré por ella —le dijo el Invierno a la Muerte— No me podrás parar —",
      "La Parca, aterrada, corrió de vuelta a casa para proteger a su flor. Al llegar, vio un colosal campo de flores que rebosaban de color. Todas se caracterizaban por diferente altura y belleza, haciendo que, cuando el viento soplara, parecieran olas de inimaginable pigmentación. La Muerte, sin acercarse a ninguna, gritó por su creación, pero ninguna respondía; sabían que el invierno se guiaría por su voz. La Parca trató de ayudar desde la distancia, pero nada ayudaba a que se prepararan para el comienzo de esta nueva estación.",
      "Con el tiempo, el invierno encontró el prado y, con un lento toque, el mundo que se había creado se congeló. La Muerte vio cómo flores de intenso color se apagaban. No podía aceptar que eso le ocurriera a su hija y, por lo tanto, rompió su promesa de nunca acercarse y se adentró.",
      "La hierba fría crujía con sus pasos. Las plantas eran brutalmente asesinadas por la glaciación. La Muerte seguía avanzando, pero ella sentía algo horrible en su corazón. No podía ser posible que toda esta belleza muriera bajo esta horrible condición. ¿Dónde estaba la calidez de la muerte? ¿El último abrazo antes de decir adiós? La Parca se dio cuenta de que todos matan, pero pocos lo hacen con amor. No podía permitir que su hija muriera sola ante el frío y, por tanto, decidió ser ella quien la abrazara mientras muriese, para poder susurrarle con ternura sobre su maternal amor. Ella encontró a su hija en el eje del prado, recordándole a su madre que ella fue el corazón que dio vida a tal color. Su madre se arrodilló con cuidado, pero su presencia ya era suficiente maldición; al acercarse, las flores que la rodeaban perdían fuerza, sus pétalos se cansaban y el maquillaje de todas ellas se escurría con temor. Finalmente, La Parca tapó a su niña con su cuerpo, formando una cúpula que la protegió del granizo. Durante todo el invierno, la Muerte abrazó a su única hija. No hubo momento en el que se apartó. Le explicó las historias que, aunque quiso, nunca contó; habló sobre su infancia en el prado y del don que nunca aceptó. Con el tiempo, el invierno fue cesando. El frío paró de helar. La Muerte se levantó con cuidado, solo para ver a su hija tumbada en la arena de aquel campo en el que ya nada reluciría bajo la luz estelar.",
      "Permaneció sentada, observando el final de la etapa que pudo vivir. Todas las flores perdieron su esencia; sus pétalos desgarrados, sus tallos separados del suelo por un cargado viento de maldad. Pero entre todas había una que conservaba su color. Pudo salvar a su hija de aquella innombrable mala muerte. Con la ternura de un abrazo logró que su hija descansara en paz.",
      "La Muerte se levantó y, con sus descalzos pasos, comenzó a marchar. Lloraba, esperando que, en este nuevo dolor, su hija volviera a brotar. Pero ya nada resurgía; tan solo se descongelaba el hielo, para dar paso a la primavera una vez más.",
    ],
  },
  {
    id: "7",
    slug: "la-luz-esta-al-principio-del-tunel",
    title: "La luz está al principio del túnel, no al final",
    summary: "Un túnel por el que todos caminamos, alejándonos de la luz de la que venimos.",
    description:
      "Sobre el camino largo que todos elegimos al crecer, los que se dan la vuelta y la certeza de que, en algún momento, volveremos a encontrar la luz.",
    accent: "var(--accent)",
    epigraph: "Leer con la canción “Le tunnel” de Sylvain Chauveau",
    content: [
      "Hay un túnel en el que todos nos metemos. Nos dicen que no hay salida y, aun así, nunca nos ha llegado a importar. Todos caminamos por él, olvidando la luz de la que procedemos para explorar la innombrada oscuridad. Algunos se cansan, deciden darse la vuelta y, al hacerlo, no los volvemos a ver más. En la distancia vemos sus siluetas, acercándose a la luz que fue abandonada por nosotros, pero los años pasan y, aun así, al darnos brevemente la vuelta, les seguimos viendo caminar. Es un camino largo el que hemos decidido, sea cual sea la dirección en la que queramos avanzar. Pero una gran aventura nos espera, por eso caminamos, por nuestras jóvenes ganas de nombrar. Nuestro futuro nos espera, nuestros ojos brillan, nos guían al andar. Hay ganas y fuerza, tenemos la suerte de tener amigos con los que marchar. Y aunque la luz se nos aleje, sabemos que venimos de ella, y en algún momento la volveremos a encontrar. Siempre podremos dar la vuelta, pero de momento nuestra casa está lejos, y por eso hemos aceptado el camino como nuestro hogar.",
    ],
  },
  {
    id: "8",
    slug: "en-el-pasillo-de-mi-casa",
    title: "En el pasillo de mi casa",
    summary: "Cada mañana, una ventana al final del pasillo deja entrar unos segundos de amanecer.",
    description:
      "El polvo, la madera y los retratos de la familia recobran su color con la primera luz del día. Cada mañana camina hacia ella, y cada mañana el sol vuelve a esconderse.",
    accent: "var(--accent-mid)",
    content: [
      "Al final del decadente pasillo de mi casa, hay una ventana que ha logrado mantener su juventud. De ella emerge el sol cada mañana, y por pocos segundos, en un pequeño instante, la melada claridad del día revela la condición del corredor. Veo el polvo surcar por los cálidos manantiales del amanecer, siendo mecido por imperceptibles corrientes que tan solo sentí al crecer. Los muebles recobran su esencia al ser inundados por la luz, volviendo a lucir el pulido color de la sazonada madera con la que fueron creados y, a su vez, los retratos de mi familia reflejan el rubio destello que brota desde el apartado horizonte. Cada mañana camino hacia el amanecer, ignorando el crujir de los cristales al pisar el suelo, tratando de acercarme a lo lejano y poder comprender el lenguaje en el que me susurra aquel dorado manantial. Pero la imperfección del amanecer es que este no es eterno. En un suspiro, el agraciado calor se difumina; el sol se esconde entre las artificiales junglas de cristal. Todas las mañanas termino en el final del pasillo; consumido en la oscuridad. Observando cómo todo lo que relucía se apaga, contemplando la puerta de mi habitación entreabierta, recordando la fina pincelada de la mañana acariciando mi cara, entendiendo que ninguna alarma logrará despertarme antes del alba, comprendiendo que tan solo despertaré con el tacto de lo inalcanzable; la transitoria luz del amanecer.",
    ],
  },
  {
    id: "9",
    slug: "el-teatro",
    title: "El teatro",
    summary: "Un público entero espera en un teatro en ruinas a que vuelva un anciano que desapareció tras el telón.",
    description:
      "Una noche de noviembre, un anciano sube al escenario, confiesa su vida y desaparece tras el telón. El público se queda esperando durante años, mientras fuera el mundo sigue ocurriendo.",
    accent: "var(--accent)",
    content: [
      "Se derrumbaba apenas con el tacto del viento, y aun así, tus ojos no lo cesaban de observar. Miles de historias narradas entre las peladas paredes del teatro, expresando con delicadeza la metaforizada condición de la humanidad. Sus venganzas, sus odios; sus ganas de amar. Los suelos infectados en mugroso verde, los asientos corrompidos por la ausencia de la gente. Cristales que fueron ventanas. Alfombras ancianas bañadas en espeso polvo. Focos apuntando a las sombras, tratando de encontrar en ellas los artistas que estaban acostumbrados a iluminar. El altar de los actores olvidado por el telón de la oscuridad.",
      "Eras demasiado joven como para recordar, pero un día de noviembre el público desvaneció. Perdidos entre los aplausos de la multitud, los actores creyeron ser los personajes de su historia. Contemplaron a la audiencia, y desde la altura de su gloria, prometieron a la audiencia que aquella noche, lo que presenciaron, no fue una producción. Ofrecieron a la muchedumbre la oportunidad de explorar un mundo lejano; y un hombre anciano, desgastado por el tiempo, alzó la mano para ser el tributo de la nueva actuación. Se guió con lentos pasos al eje del teatro y una vez los ardientes focos escocieron sus pupilas el público aplaudió. El hombre expuesto a todos, fue preguntado por su vida, y mientras agarraba tímidamente su desgastada chaqueta, tratando de buscar refugio en ella, contestó. Dijo que desde su infancia no disfrutaba, que mientras esperaba a su muerte, venía a distraerse al teatro a ver las vidas que aunque quiso, nunca vivió.",
      "Su voz resonó por el antiguo teatro, infectando con espesa tristeza los corazones de la multitud. Largos segundos devoraron la felicidad que había sido cultivada por el previo acto; la realidad volvía a adentrarse entre los fríos asientos, recordando a todos el gélido mundo que les esperaba una vez escaparan de las terciopeladas paredes que les protegían del invierno. Todos, callados, observaron al hombre internarse entre la gran muralla de tela que separaba fantasía de realidad, contemplando su cuerpo ser consumido por el maleable telón que rebosaba de escarlata esencia. Unánimemente, la audiencia reflexionó sobre la existencia del antiguo hombre, del abismo que sus palabras pronunciaron, de la soledad que terminó aceptando. Una vida desgastada por la fricción que las sombras ejercieron sobre sus sueños. En su última etapa de adultez, decidió desaparecer frente a todos al otro lado del teatro, ver desde un escenario con sus cansados ojos a la gente que por vergüenza a ser juzgado, nunca saludó. Su última mirada, dirigida a un público de extraños, fue pidiendo perdón.",
      "-oo0oo-",
      "Refugiados en la absorbente magia del teatro, nadie pensó en el mundo tras el cristal. Pero aquella noche, la hierba heló. El cielo nocturno brilló con tenue fuerza; las desnudas estrellas formaron una nueva constelación. Un zorro blanco, caminando por el marchito trigo encontró un árbol sin corteza, herido por el granizo. Descansó al pie de sus excavadas raíces y, al sentir el tacto de sus decayentes ramas, se dio cuenta de que, por casualidad, había descubierto el árbol donde su madre lo crió. Se adentró en la gélida carcasa de su antigua vida: un tronco inerte, acechado por un alma que anhelaba resurgir. Se sumergió en él, y el calor de su piel le brindó nueva dureza. Atrapado por las garras del invierno, el árbol floreció. Pero, consumidos por el hechizo de un telón vacío, nadie en el teatro lo vio. La espera al anciano se volvió la esencia del acto. Horas declinaron a minutos. El mundo se paralizó. Todos, desde sus butacas, contemplaban un escenario deshabitado, esperando con ansias una nueva narración.",
      "Pero pasaron largos años. Las arrugas se pronunciaron, los párpados comenzaron a pesar y la última mirada de muchos fue dirigida al vacío que sus expectativas pudieron crear. Con el tiempo, las suntuosas paredes se deterioraron. Las manillas de los relojes se aflojaron, entorpeciendo su velocidad. El edificio que fue símbolo de esperanza terminó corroído por los años. Su techo finalmente derruido. Y entre escombros de madera y tela, quedaba una sola persona que, aún desde su butaca, apreciaba la nocturnidad. Desde las ruinas contemplaba las estrellas, permitiendo que las constelaciones le contaran historias del más allá. Pasaron semanas. Durante el día observaba el vacío acto, y en la noche, el cielo estelar. Llegó el solsticio de primavera, trayendo consigo, en su primera noche, una feroz aurora boreal. Observó sus ardientes colores iluminar el cielo, sus pinceladas en el negro abismo astral.",
      "El hombre perdió el sentido entre tanta belleza. No concebía que el mundo pudiera expresarse con tal intensidad. Había un universo ahí fuera, y él mismo se había aislado de tal preciosidad. Con temblorosas fuerzas logró alzarse de la polvorienta butaca. Y, en su intermitente locura, decidió avanzar. Caminó entre los restos del único edificio que pudo hablar, recordando las historias que desde niño siempre lo inspiraron a imaginar. Era ahora, de adulto, a las puertas del teatro, cuando entendía su mal. Su fallo, al igual que el del anciano, fue esperar. Sus labios no eran diferentes a los de los actores. Los suyos también podían narrar.",
      "Miró una última vez al descolgado telón, donde el anciano logró escapar, y su mano empujó la puerta, llevándolo al mundo en el que todas las historias se hacen basar. Al salir del teatro, la primavera lo esperaba con ardor. Pero, entre todos los árboles, solo uno permanecía helado, aguardando el calor del invierno para que sus hojas pudieran brotar.",
    ],
  },
  {
    id: "10",
    slug: "goldie",
    title: "Goldie",
    summary: "Un niño toca cada noche en la playa, intentando que la Luna llore con su música.",
    description:
      "Mientras sus padres duermen, un niño se escapa a la orilla para tocar a la Luna. Sin saberlo, su canción despierta los recuerdos y los sueños de todo un pueblo costero.",
    accent: "var(--accent-mid)",
    content: [
      "En esta cálida noche de verano, notas musicales surcan el océano hasta perderse en el mar. Un niño con excelente destreza toca su instrumento, tratando de ver si su melodía puede hacer a la Luna llorar. Sus dedos acarician gentilmente las cuerdas, que tras tantos días, ya sabe hacerlas cantar. Sus ojos, perdidos en el estrellado abismo que es el cielo, convencido por sí mismo, que sólo puede medir en llantos la calidad del arte que pudo crear. La calmada brisa de la noche se conjuga con el ritmo de las olas. La arena esparcida por el gentil tacto del viento viaja como leve niebla a apenas centímetros del suelo, adentrándose hasta las profundidades del tímido pueblo, donde ancianos sin sueño, desde lo alto de sus balcones, beben sin que sus familias lleguen a despertar.",
      "Es siempre en las vísceras de la noche cuando el crío decide escapar; con pestillo, sus padres cierran la puerta donde duermen, y al escuchar el metálico ruido proveniente del pasillo sabe que puede marchar. Se escapa por su ventana y, tras un breve salto, la húmeda hierba palpa sus pequeños pies. Bajo la luz de los astros, camina por la playa de arena blanca, contemplando, mientras avanza, cómo las sombras que habitan bajo las palmeras, osciladas por el viento, le comienzan a saludar.",
      "Todas las noches, en la orilla del pueblo, la entrada de mar, la noche evoca su cantar. Y sin saberlo, mientras únicamente se enfoca en la Luna, el mundo empieza a cambiar. En el pueblo, las finas cortinas de tela son mecidas, no por la brisa, sino por su entonar. Las cálidas farolas florecen su tenue brillo, iluminando las estrechas calles donde los gatos, al escuchar la melodía, se acurrucan para descansar. Niños que no duermen, sin cerrar los ojos, comienzan a soñar; aquellos ancianos que beben son recordados a la memoria que querían olvidar. Un pequeño pueblo costero que solo brilla en la oscuridad. Un faro ilumina intermitentemente desde la lejanía, alumbrando discontinuamente las habitaciones donde madres sin hijos al fin logran reposar.",
      "Desconocidos unidos por un niño; todos saben la razón de su cantar. Y, aunque esa sea triste, es al escucharlo de madrugada cuando los habitantes se logran inspirar. El niño no sabe del efecto de su canción; tan solo mira a la Luna, la cual le responde con insensibilidad. Pero, si se fijara en los astros, vería que son ellos quienes, entendiendo su historia, lloran, creando una lluvia en la galaxia que todos, atónitos, no cesan de observar.",
      "Habrá un día en el que la luna dejará de ser su musa. Y ese día, por muy lejano que sea, llegará.",
    ],
  },
  {
    id: "11",
    slug: "dont-ever-change",
    title: "Don’t ever change",
    summary: "En un prado inundado por las tormentas, un hombre le pide a una máquina que nunca cambie.",
    description:
      "Todo a su alrededor se transforma, se hunde en el barro o desaparece con el tiempo. Solo el ruido constante de una máquina de metal le ofrece la única certeza que le queda.",
    accent: "var(--accent)",
    content: [
      "Su alma levitaba por el alivio de su voz: su perfecta uniformidad, su predecible función. El barro consumía con ansia sus desgastados zapatos. La hierba, verde como nunca por la lluvia de las impredecibles tormentas, esparcida sin armonía sobre aquella húmeda tierra. Lombrices avanzaban entre el deslizante terreno, erosionado por la constante necesidad del mundo por transformarse con el tiempo. El cielo, parcheado por una inconstante mancha gris, transicionaba continuamente de color, mostrando ante sus ojos un interminable e iluminado humedal, tan solo para cubrirlo de nuevo. Árboles en la distancia chorreaban manantiales desde sus caducas hojas. La transitoria luz del cielo iluminaba con lentas ráfagas el prado, dando la tranquila sensación del ralentizar del tiempo. El viento ondeaba el casi ahogado pasto, silbando una inconsistente melodía.",
      "Entre los aullidos de la brisa, él escuchaba su plateada voz: su constante maquinar, engranajes fríos frotándose ininterrumpidamente entre ellos, creando una única sonoridad que la inconsistente naturaleza no podría recrear. Una cadenciosa melodía de percusión industrial, destrozando los impredecibles cantos y silencios de la naturaleza. Sin acercarse, él podía sentir el inhumano tacto del aparato. El álgido y ferroso tacto, pulido hasta ser la lisa y continua maquinaria que es. Un obelisco de metal diseñado para durar, idéntico al día de su creación. Ningún rasguño ni fallo, una inmutable genialidad perdida en un campo sumergido por tormentas.",
      "Un mundo en constante cambio, sin garantía de evolucionar. Todo termina hundido por la lluvia, enterrado entre barro y corroído por una insensible naturalidad. Ve cómo aquello que siempre estuvo comienza a deslizarse entre sus dedos. La garantía de la maquinaria, de ser la única creada por una única razón y ejercerla hasta desaparecer. Desde años, el mundo fue siendo moldeado por el marcar de los minutos. Animales migrando en invierno para no volver. Árboles caídos sin tener semillas con las que volver a crecer. Un cielo que ni de noche estrellas puede prometer. Es un mundo en movimiento y él, desde su ventana, lo observa atónito, dudando si será la misma vista cuando el sol decida amanecer.",
      "Hoy el campo es asediado por volátiles tormentas. Incontrolables rachas de lluvia que, sin patrón alguno, rocían hasta más no poder. Los claros de la llanura son engañados, acariciados en un principio por el agua hasta darse cuenta de que se están empezando a sumergir. En un mundo sin certezas, él solo pide que la máquina nunca termine de ejercer. Que sea quien sea, y su maquinaria no pueda envejecer. Que los vibrantes sonidos de gas comprimido y rítmicos silencios duren hasta que el prado no sea lo que es.",
      "“Jamás cambies” —susurró a la única certidumbre que el hombre pudo tener. Lloró simples lágrimas antes de marcharse, la lluvia no cesaba de conquistar. Su llanto camuflado por la permanente metamorfosis de la tempestad. Gigantes charcos compuestos de demasiada lluvia y escasas lágrimas se anclan en el barro para crecer. Apenas se ve la verde hierba que, en un principio, le atrajo a ese remoto lugar.",
    ],
  },
  {
    id: "12",
    slug: "two-beautiful-bodies",
    title: "Two beautiful bodies",
    summary: "Sobre el peso de lo que nunca se dijo y dos almas que vuelven a encontrarse junto a un río.",
    description:
      "Hay un vacío que crece mientras no tiene nombre. Un hombre recuerda la noche en que, al final de un bosque oscuro, escuchó a dos almas reencontrarse y entendió por qué hay palabras que nunca deben quedar sin decir.",
    accent: "var(--accent-mid)",
    lang: "en",
    content: [
      "There is a strange weight within what we call a memory, a burden without measure that, though it has no shape or dimensions, can still be felt by the space it occupies within the soul. Some carry this empty weight without ever understanding why. And it is those who cannot understand the feeling who eventually perish beneath it. For it is a void that grows until it forces the soul from the body, leaving the beauty of the body untouched. It is a suffering no action can describe, and therefore, unable to find a language through which to reveal itself, it becomes fatal to those who bear it. No one can understand the language of words that were never spoken. In the end, all that remains is a lonely beautiful corpse, left behind by a darkened mind that could never find the words to speak.",
      "Time is what makes this uninhabited feeling grow. It allows you to find meaning to your pain; it decides whether your suffering is worth dying silently for. The tears will always come heavier when you do not know the name of your emptiness. You will try to fill yourself with a salty remedy. But it will never be enough. Because until you know its name, you will never know how deep it truly goes.",
      "Though the grey in my hair now betrays my mind, I remember myself as a young man, walking through a dark forest. Not knowing what I would find, I kept walking until I reached its end. There, with no trees left and a river before me, I heard the cries of two souls who had finally found their way back to one another. They breathed between sobs and gasps. They held each other's harmed bodies with all their strength, their fingernails digging into each other's backs, knowing they could never allow themselves to escape again.",
      "I listened through an entire night to words I now know must never be left unsaid.",
      "When morning came, those two souls had found their strength again. Their bodies, as well as their minds, were healed. Because they knew that the emptiness that always followed them had a name, one that, on that night beside the river, had finally been met again.",
      "Now, I believe you understand why we must give feelings a name. No language, no action, can save you from a feeling that was never allowed to be heard.",
      "Time had helped those two souls understand that each other were the reason for their pain. Only once they knew the name of their suffering were they able to express it to the world. Their bodies suffered along with their minds. The world shared their pain. No tears would ever fill the void that she had ever made.",
      "They found each other because of a whisper few people comprehend. But without a name, they would never have found each other. And the black abyss of emptiness would have swallowed them whole.",
      "Leaving behind two beautiful bodies, lost somewhere in different corners of the world.",
    ],
  },
];

export function getStory(slug: string) {
  return stories.find((story) => story.slug === slug);
}

export function getOtherStories(slug: string, limit = 3) {
  return stories.filter((story) => story.slug !== slug).slice(0, limit);
}

export function formatStoryDate(iso: string) {
  return new Intl.DateTimeFormat("es-ES", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(`${iso}T00:00:00`));
}

/** Separadores como «—oo0oo—» que dividen una historia en partes. */
export function isSectionBreak(paragraph: string) {
  return /^[-—–]*oo0oo[-—–]*$/.test(paragraph.trim());
}

export function storyPath(slug: string) {
  return `/historias/${slug}`;
}
