import type { StoryTranslation } from "@/lib/stories";

/**
 * Traducciones al inglés, por id de historia. Lo que falte se toma del
 * original (por ejemplo, el texto de «Two beautiful bodies», que ya está en inglés).
 */
export const storiesEn: Record<string, StoryTranslation> = {
  "1": {
    title: "That Meadow Where We Lived",
    summary: "A man who no longer remembers his childhood is visited by a shadow that paints his memories blue.",
    description:
      "A stolen cigarette, a leafless tree and a white flower in a summer meadow. Years later, in the city, a shadow begins to visit him with paintings of his life and a brush soaked in the color of the sky.",
    content: [
      "Lately I have been trying to remember.",
      "I let waves of nostalgia strike my arid memory, hoping they will soak my mind with memories I can only dream of sinking into. Endless sleepless nights in which I keep my distance, watching thoughts that were once mine, begging to be absorbed by them, but they are no longer what they were, they are not what I felt, they are mirages of a life that no longer belongs to me. In idle moments I close my eyes and let myself be shipwrecked in the sea of memories in which I so long to drown. The weather is calm, the breeze pleasant and, as a result, I suffer knowing my dream will never come true. I am a castaway sailing an ocean in harmony, praying that in some fleeting moment the water will splash my dried-out sailor's face and I will finally feel like a captain in times of storm again.",
      "The days pass at the speed of hours and I, lost in a world I never quite understand, simply contemplate the garden of memories in which I used to lose myself as a child. The sad petals, tired of waiting for me to return, wither, forcing me to forget what I once was. But between death and drought there is a flower that, against all odds, does not drain away, a memory that still radiates its young innocence. A memory to live for.",
      "I remember the burning summer sun lighting up the vast horizon, warm glows wrapping the beautiful world I came to belong to. Not a single cloud darkened the luminous spectacle the sky offered that day, and the wind, to make up for the July drought, tenderly rocked the field around me. That afternoon, while my grandfather celebrated his birthday, I managed to steal a single cigarette and a lighter from the grown-ups' table and rode my bicycle to the meadow where I had once learned to tame it. It was at the age of seventeen that I sat down on the yellowed, withered grass of the field where I once lived my childhood, and leaned my back against the only tree in the landscape. Not a single leaf sprouted from it.",
      "That afternoon I chose to lean against a corpse, and for some reason it is the warmest memory I have.",
      "For hours I was an extension of those lifeless branches, serenely contemplating the cigarette, raising it into the air, forcing my gaze to lose itself in that clear sky that always dressed in blue. All afternoon I could think of nothing but that simple color. How was it possible for thousands of people to love such a common color? What is so special about loving what everyone has? Everyone, my family included, fell in love with something that never managed to captivate me. I asked anyone I could, trying to understand the hypnotic reality everyone else belonged to. What is it you see, why do you fall in love with something that cannot see you? No one answered what I believed was an easy question; they couldn't believe I didn't feel what they felt, they couldn't imagine a life without the blue of the sky.",
      "With time, the summer began to die and with it my curiosity. The last sunset before autumn arrived and, among the final rays of sun, I heard the only answer I ever received. “It's comforting,” my grandfather murmured, almost to himself, as he contemplated the bare horizon fading before us, both of us sitting on wooden chairs in the heart of the wide meadow. I remember looking at him after his simple answer, confused, and being answered only by the violet color of nightfall reflected in his dimmed eyes. For long hours silence ruled the field, accompanied by the serene presence of the wind. I decided to get up slowly, trying not to wake my dear old man, but I was startled by his calm voice: “Do me a favor,” he recited as he rested with his eyes closed. “Look in my room for a small book, and bring it to me when you find it.”",
      "Under his pillow I found a collection of photographs.",
      "He thanked me with his smiling eyes and said goodbye with a slight wave of his hands. As I left I could see how that man looked tenderly at the book, but even from a distance I saw his gaze tinged with sad thoughts I never managed to decipher. On that last summer dawn, my grandfather never opened the book. He only embraced it, like a good mother holding her frightened child, and chose to watch the lonely road along which we had all arrived months before.",
      "—oo0oo—",
      "I took the first drag of my life looking at the dead grass on the ground. The dry smoke of the cigarette flooded my unsuspecting lungs and I could do nothing but cough, watering the withered grass with my bitter saliva. I smiled, a slave to my new vice, unaware that on that day the sky changed color. In a matter of minutes, the much-loved blue that had caused me so many questions was suffocated by a deep darkness. Thick clouds ruled the firmament, engendering an artificial night. Asymmetrical gaps between them let the burning heat of the sun keep lighting the landscape. An image etched in ink inside me: thin threads of light piercing the colossal mountains of cloud, fighting to light up the immense gloom that had been laid down when I smoked. The rain soon became part of the tragic scene and so I decided to leave. I stood up carefully, trying not to hurt the old tree, thinking that with any luck my company had inspired it to let new leaves grow. Once on my feet I noticed a nearby beam of light. My curiosity made me visit it and, as I drew closer, I could do little more than smile. At my feet, a white flower with frail petals whose edges were signed with tiny golden ripples. I watched it dance subtly under the impact of the raindrops, like a confused ballerina unable to remember her next step on stage.",
      "I smoked my last drag contemplating the glorious display of lights that still illuminates my sleepless nights. I lowered my head, crouched down and rested what was left of the cigarette at the foot of the only flower brimming with young life in that pasture, thinking the rain would put it out. That afternoon, as I left, I did not look back. With every step I took, the clouds darkened my world, and it was amid the gloom of the landscape and the crunch of my departing steps that I saw out of the corner of my eye how the only flower that could ever be kept shining in the darkness.",
      "—oo0oo—",
      "The world grew pale once I left the meadow where nothing shines anymore, the field that was lost among the clouds. Since that day, no color has managed to awaken new obsessions; no light has guided me to any flower. I became a prisoner of monotonous streets where everyone lives in silence, afraid of waking from the loneliness in which they die. It is a sad world of the sick and I, with a cigarette between my lips, was lucky enough to find the cure.",
      "Just a few months ago I left my apartment hoping to find the way out of this place. I grabbed the pack of cigarettes and the lighter and walked aimlessly through the labyrinthine streets everyone wants to escape, noticing the tall gray buildings where children grow up, pitying them for only being able to play on cold metal stairs. I spent a short while looking at the great concrete structures that made up the metropolis in which I smoked, but soon it began to rain. I threw the cigarette away unhurriedly and walked back home, reflecting on the vice that had forced me to get soaked in that remote corner of the city. Why was I letting myself be killed? I couldn't understand how I was still addicted to those tasteless cigarettes if they didn't give me the freedom of so many years ago.",
      "As I reflected, I was briefly distracted by a small family. From a distance I watched a mother try to shelter her son from the cold rain, walking from doorway to doorway, holding her boy by the hand, but the little one would stop every now and then in the middle of the lonely street, letting go of his mom to gaze intently at the warm color the streetlights radiated. The boy got soaked while he looked restlessly at what one day would stop seeming interesting to him. I could swear that in that moment I saw the streetlight shine a little brighter, trying to tuck its only admirer in against the cold around him. The mother went up to her son and he, without taking his eyes off his new obsession, raised his arm to take his mother's hand. They left as quickly as they had come and, once they were gone, the streetlights shone less brightly. They had no reason left to shine; no one would ever look at them again. That day, for a very few seconds, I was able to see what few ever get to contemplate: the wonder of the ordinary being discovered once more.",
      "At last I reached my building. The cold had seeped through my clothes, forcing an unpleasant feeling onto my skin. I went up to my flat shivering and, once in front of my door, I realized it was open. As I slowly entered my home I saw a man, a silhouette standing in front of the only window of my small apartment. Anyone would have been terrified to see a shadow that was not their own, but for some reason I felt peace. The stranger held a small canvas in his hand, partly covered by the long coat he wore, keeping me from seeing what the man had painted. The shadow looked at me with empty eyes and, in his calm voice, asked me to sit down. I took a seat on a small chair while he sat across from me in the armchair.",
      "He looked at me without saying a word, though his eyes spoke languages anyone could understand. There was a deep sadness accompanied by traces of weariness in his dialect. After long seconds of calm, he slowly began to unveil the canvas.",
      "What I saw that afternoon stopped my world.",
      "The vividly colored image that man showed me was of the field I believed would never shine again. His art was a lost memory and, seeing it, I felt a warmth that only a pair of arms can give. I felt the cold and the dampness I had gathered leave my body, leaving a pleasant sense of calm in my heart. I kept looking at the illustration with incredible enthusiasm, stunned to be able to see again what I had lost so long ago. But between my tears and smiles that impassive shadow watched me with pain. I looked him in the eyes, confused, as he took his brush out of a small pocket. I didn't understand what was happening but he took care to answer without words. From his great coat he took out a small pot of paint. A dark color, like the depths of the ocean. He began to dip the brush delicately into that great, beloved color. My confusion turned into terror. I couldn't believe I was about to lose what I had never managed to recover. I begged him from the depths of my soul to stop, not to do what he was about to do. “Let me keep it, please,” I sobbed with all the strength my frightened body could gather. “Why do you want to remember?” he replied in his sleepwalker's voice. “I need something to live for,” I said, crying, pleading with his soul to let me remember who I had been. The man stopped stirring the paint with his brush. He looked at me and began to ask me about the details of the memory he held in his hands, but I could not answer a single question. The memory, though mine, was distant. Time had passed and the details no longer existed. For every unanswered question, the man painted a blue line, thick and opaque, covering whatever color came before it. The intensity of the memory faded into a blue that erased every emotion and every contour of what I had lived. Late in the afternoon, when the cold light of dusk came in through the window, the painting ended up a single color and I was once again the owner of just one memory.",
      "The man kept coming, each time presenting memories I would kill to live again. On every visit he showed me paintings summing up my life, but every time he questioned me, I suffered the stab of the brush once more. One day, the man drew a young woman. “Did you know her?” he asked me in his unhurried voice. When I saw the drawing, my soul filled with joy. Yes, I remembered her! I told him everything, every tiny detail no one but me could know. I had to prove I remembered her, I wanted to prove she still mattered after all these years; forgetting her was not my choice, it simply happened. I fought for her memory, I talked for minutes on end just to save her from oblivion, but after everything I said he only asked, softly: “What was her favorite color?” I felt a deep weight in my chest, almost as if my heart had been sunk. I thought I could defend her memory, but because of a question I never asked, there is now one less person I can remember. “I don't know,” I replied, and the man, with visible sadness, began to paint the canvas once more.",
      "With time, the visits became less frequent; there were fewer and fewer memories left to fight for. On one of the last days he came, he showed me a painting. He asked me about it, but I didn't want to answer.",
      "“I never wanted to forget all this,” I told him.",
      "He answered:",
      "“I know you didn't want to forget; no one usually does. But time heals everything, even what does not need healing. The way you look at the paintings gives you away. I know you treasure everything that once happened to you and that you long to hold hands again with those strange feelings you no longer recognize. But you have to understand that what has happened to you is no coincidence. You chose to leave the countryside, your family. Not out of malice, but out of the hope of your young heart. You wanted to thrive and to travel, to live the life you longed for so much. You packed your suitcase with hope, but who would have said you forgot to bring what you would need most? You don't remember because there is nothing to bring the memory back to you; you brought nothing that would help you look back. In that house in the meadow, the one I have painted hundreds of times, every corner overflowed with memories. Present and past blended together, making it hard to forget any little story. You thought it would always be that way. But now that you live on a blank canvas, nothing gives you back what you lost, nothing resembles the color of your home. Everything is new, but that is not a bad thing. Young as you still are, you can learn from what has happened to you. You had one great failing in your former life: you never asked. People vanish from your mind; you don't know who they were, those who tucked you in. A mother, a father, even a grandfather. You knew they were your family, but you never wanted to learn more. You stayed on the surface. You never asked about their favorite food, though they asked about yours; they knew everything about you while you know nothing of the melodies that made them dance or the books that made them cry. Because you never asked about anything mundane, nothing in everyday life can carry you back to the past. Had you asked about harmonies, you would remember your grandfather every time you heard a song; he loved them. About food, you would remember your mother's love of cooking, and about poems, your father, whenever you read any book about the Second World War. The only time you chose to ask was about that color you believed was so beloved. But you did it too late; I had already asked.”",
      "He stood up on his way to the door:",
      "“I have no more memories to ask you about, nor paintings to take from you. It does not please me to know you have lost everything you loved so much, but you did little to avoid me. No one usually does.”",
      "After his farewell, the shadow of oblivion left, forcing me to reflect on everything he had said on that first spring afternoon. I never understood who that blue shadow was, but it is because of him that I now understand my family. They did not love blue; they simply accepted it as part of their lives. They all lost their battle against the vast color of the sky. “It's comforting,” my grandfather said, speaking of his defeat. He no longer had to fight against oblivion. He chose to forget, because he had grown tired of defending his memories. My family surrendered, and what I believed was their favorite color was the flag of their sad defeat before that shadow. It hurts me to know they lost to oblivion, and that is why I don't intend to concede it any new victory. I will fight for my new memories, because now I understand that if after a long life all we have left is memory, we must make it easy to find. That is why that young boy will never forget the afternoon he watched the streetlights while it rained, because he will always be able to see them from the window of his home, and that is why I will never stop smoking.",
      "After all these months watching my memories disappear, I took it for granted that every moment I had lived before my thirtieth birthday, the day I met the man in blue, had been lost forever on an eternal canvas the color of the sky. But for some reason I don't understand I was wrong; I am beginning to remember you. I see blond hair swaying in the field where I once grew up. I don't know what it is I see, I don't know who you are, but I know there was a time when you were everything to me. Your smile, your face, are becoming more present every day. I should be glad to be able to remember you, but I am afraid of losing you again. I never asked you your favorite color and, for some reason, you are all that remains of who I was. In idle moments, I close my eyes and your memory bursts into my mind, adrenaline runs through my veins and I race through my whole house, terrified by the thought of forgetting you and giving the man in blue a reason to return. Frantic, I search for something to associate you with, but there is nothing valuable enough to remind me of you, so I have decided to keep you in the only place I know will never lose its importance, a place that will never drift away from me. Some time ago I wondered about my addiction to tobacco. I never knew why I couldn't quit, and it is only now that I understand I am addicted to a past life, and that with every drag I am returned to it. I have decided to shelter you in my mind, in the only memory that will not fade. I will always remember you as the flower that burned at the touch of my first cigarette; I will always remember you for as long as I am willing to kill myself. I promise I will look for you in this new life and, if luck smiles on me, I will be able to find you again. For now I am learning to draw for this new adventure; I will not allow myself to forget anything that happens to me. When you see me, if you remember me, you will see how much I have changed since we were children, and I promise to draw with the one you name your favorite color. I will remember you by whatever moves your soul and you will remember me by my drawings, my art. The future is exciting, I am ready to begin this new stage of my life, but I still don't know where to find you, and so I simply perfect my drawings while I smoke, to make sure I will have something to remember with. I am sure of only one thing: I will keep smoking, I will do it until we embrace again. So that you and I, one way or another, whether in my memory or in the present, may see each other once more in that forgotten meadow where we grew up hand in hand so long ago.",
    ],
  },
  "2": {
    title: "Sands Without a Beach",
    summary: "Sitting on a darkening shore, someone lets the sand cover them while remembering a pair of black eyes.",
    description:
      "The beach fades beneath a closing sky and the sand begins to cover him. In the blackness of the landscape, a pair of eyes reappears in which part of him was lost forever.",
    content: [
      "I don't know how long ago I got lost. Sitting on the shore, a few meters from the sea, I watch the horizon being stalked by a primal pain that eternally defeats oblivion. I feel its strange thickness dwelling in the clouds, sliding across their exposed skins. Corrupting them. Forbidding any fragile gap from existing between them. The white sky that once flourished has become a harsh and grieving black brushstroke that consumes the essence of what it was. The opaque firmament grazes the level of the sea and the stars have become immaterial. I can feel in my chest the new creation the sky is engendering. Something incomprehensible is about to be laid bare before my eyes. A coded essence, indifferent to me, which forces me to choose between the uniformity of the gloom or the unsettling eminence of creation. The wind drags the charred sand of the landscape over my skin; it piles slowly upon my body, covering me, trying to sink me into its cold essence. The beach has grown tired of me. It does not want me in its new world. The sadness of not being chosen flows into my acceptance. I decide to keep watching what surrounds me. I hear the rattle of calm sliding across the gravel. It resembles the beat of an arrhythmic clock. I think of the limited time I have left on this beach on the verge of extinction. The sand keeps consuming me, but I don't move; I am in no hurry to flee my throne of coal. I watch the extinguished light of day enter the ocean, losing itself in the ashen tide, never to return. The water wears the only color that bewitches my wronged soul. The waves, scraping against the rocks, imitate the song of the sirens I never saw. I feel tired.",
      "The blackness of the landscape stirs in me the memory of her eclipsed marble eyes. I wonder what has become of her. I came to contemplate diamonds that were named pupils; I made out in her eternal night the promise of day. The landscape reminds me of her name. Perhaps that is why I feel so calm letting myself be buried by the dark sand; to melt once more into her black eyes. To let my soul shed the weight it carries, to be immersed in her gaze and find myself again in the galaxy of her iris. To be once more that astronaut who got lost in her nebulous eyes. To visit secrets shaped like planets, to witness the sunsets of other worlds. She gave me a universe that part of me never wanted to leave. A fragment of me broke away to explore her fantasy. That essence of mine cut off communication with myself to lose itself in that beyond. Part of me became a wanderer in her glass eyes.",
      "From today, the beach where I used to watch the stars hoping to find myself is clouded over. The horizon no longer shines as it used to; it tells the story of my bitter truth. Looking at the sky every night, dreaming of seeing my reflection in the stars, so I could finally recover myself. But there are times I wake up thinking: what if I am the astronaut who never wanted to return? What if this beach is her world, and she is beginning to forget me? I don't know if I am myself, or what I could never save. The sand has stopped consuming me. The wind blows the melody of loneliness. The tide rises, grazes my feet: it is urging me to swim. Tomorrow when I wake I will have left the sand. I don't want to see the new world that is about to form. Though I don't know if I'll return home, looking at the sand or swimming through that sea.",
    ],
  },
  "3": {
    title: "Seaweed",
    summary: "A poem about a girl the sea does not want to give back.",
    description:
      "Hair and clothes rocked by the tide, a girl who decided to play, and a silent war between the shore and the ocean to keep her memory.",
    content: [
      "Hair that was once straight is being rocked by the tide.\nIt spreads like cracks through the cold realm where it floats.\nGray water reflecting the color of the sky:\na dark grayish, a bonfire's smoke.",
      "Long hours faded her clothes\nHer young skin, cracked by the salt.\nIn the distance the waves roar; they weep.\nFor her actions: consequences no one could imagine.",
      "Her legs are sunk in a black abyss.\nRed eyes, though dead, gaze into the deepest sea.\nShe, only a little girl, who smiling, decided to play.",
      "Hair and clothes rocked by the tides want to guide her back home.\nBut the current, ashamed, anchors the girl, does not want to reveal her.\nIt doesn't want anyone to find her; for her black eyes to shine again.",
      "Between shore and ocean; a war.\n(Everyone wants her memory, everyone wants to care for her.)",
    ],
  },
  "4": {
    title: "The Limit of a Poet",
    summary: "An artist who devoted his life to portraying someone discovers the limit was never the pencil.",
    description:
      "Pencils, ink, photography, glass and dance: no art can describe her. Applauded for a work he considers a failure, a poet decides to dedicate to her the only thing that will never cease to exist.",
    content: [
      "I always adored the idea of the sharpest pencil; it was an obsession that lingered in my head from the moment I aspired to be what I am. I told myself that with it I would manage to portray the indescribable in detail, that drawing the intangible would be as easy as being inspired by your voice. I spent countless nights dreaming, thinking I could at last draw any tiny detail without error. I lived in a bubble of hope until I met your eyelashes; it was they who slit my bubble of illusion. Something as simple as a pair of wavy lines terrified me; they looked nothing like reality. Any route to your eyes was inconceivable, thousands of strokes that, though simple, made me fail. I spent much of my life focusing on minuscule details and still I could not even draw the hair I always loved. I tried your eyes, but I could never make them deep enough. Thousands of ruined canvases and watercolors, none matched the touch of your skin. I understood the limit was the pencil, so I changed it. I tried to write an intimate ballad in blue ink, but the dictionary lacked the words, just as the musical scale lacked the notes. I tried to photograph you, but every image ended up saturated by your radiance. Any image of you is like seeing a galaxy flooded with color. I sculpted your being in glass, but I never found glass that resembled your purity, and I created hundreds of choreographies that ended up being an offense. There was no human movement that described your beauty. In time I realized that the limit of a poet is not his pencil, but his hands. For however much hope my eyes shine with when I see you, it is my pulse that dictates the result. For thousands of years humans built cities out of mud. I don't understand how I couldn't draw you with the pencil that inspired me so much. It wasn't a lack of desire, it was a lack of skill. I am a dreadful artist and no one seems to notice my flaw. After a whole life of work, I fell short, and the others applauded as if it were the finished work. They didn't realize the story was missing more. They don't know there is much more to tell. They live in ignorance of my art and it is a pain that will always stay with me. If the whole world burst into applause at my attempt to describe you, I cannot imagine the universe's reaction to unveiling you without fault.",
      "I am famous for my unrecognized defeat, a simple dictionary I created so I could define you; hundreds of words that don't exist, but are needed to know you, words you engraved in the depths of my memory every time I saw you. I am not proud of reducing you to just a few invented words, but that is all I could do for you. You are everything I could not draw: the twenty-eighth letter of the alphabet, the nonexistent musical note. That is why, however much the public loves it, I cannot dedicate the book to you; it would make no sense to dedicate to you the work I never managed to complete. It will always hurt me not to have been able to create a new art for you, but that is my cross to bear. I cannot sign it, not with pride; I am not the artist everyone admires, I am a dreamer, a fraud who can never portray you. That is why I will not create again, for it is all the ideas still floating in my mind that live in their fullest splendor, since they live in a place where there is no attempt to express them to anyone but me. I ask you to trust me, for I will never again declare my feelings, but I promise that if you look into the depths of my pupils you will see your reflection in colors that never came to exist. I will dedicate to you what will never cease to live, for paper will rot with time and words will fly away on the wind. I dedicate to you what will always exist: my passion, my ideas, my love for you.",
      "The limit of a poet was meeting you.",
    ],
  },
  "5": {
    title: "The Uncertainty of Heat",
    summary: "A poem about a mirage in the desert.",
    description:
      "Between the burning sand and the refraction of the heat, a figure in the distance that seems to come closer and disappear, and a question in the cold night.",
    content: [
      "Between the suffocating warmth and the dazzling glow of the sunset\nWhile the orange sand cut me as the wind swept it along\nAnd my feet were buried in the ground\nI thought I saw you in the distance, watching.",
      "With barely any strength I dragged myself across the sand\nBanishing the grit from my burned feet\nAnd between the refraction of the heat\nAnd the shadows of the dunes\nWith tearful eyes, I thought I saw you look",
      "But as I took a surrendering step,\nForcing myself to feel the burning of the wounds\nThat had already stopped hurting,\nI looked at you in the distance\nHoping to see you near\nBut you seemed to disappear.",
      "I was tired,\nI lay down on the sand\nIt was no longer worth the climb",
      "That night, as the cold curled around me\nAnd the stars shone, fighting to stand out.\nI thought of that mirage, reflecting so I could ask,",
      "Whether you're not here because you're drifting away\nOr because you were never here at all.",
    ],
  },
  "6": {
    title: "The Cold of the Blade",
    summary: "Death, weary of her work, sees a flower grow from her own tears.",
    description:
      "The Reaper walks barefoot through the meadow where she was born. From her tears sprouts a small orange flower she promises never to touch, until Winter whispers that it will come for it.",
    content: [
      "Death walked barefoot through the blue meadow where she was born. Unhurried, she made her way through the dense grassland of her childhood, which, with immense beauty, was bathed in a cool glow. It was the moon, companion of her girlhood, that lit up the night, welcoming back the friend she had always adored. Death wandered slowly through the memory of her home; sad tears flooded her eyes, for she finally understood that no one could be guided by her hand to the only place where she had ever felt peace. The wind tried to console her by blowing a gentle breeze, tenderly rocking the meadow, trying to softly brush away her salty grief. She did not deserve to drown in sorrow. In the countryside, everyone knew the Reaper and her kind heart.",
      "That night, with grieving eyes, she watched the subtle shimmer of the stars and confessed to the night that, by mistake, she had forbidden someone who should not have been from admiring the sky she had always loved. That evening, before she wept, the Reaper had visited a small house on the hillside. She never wanted to use her scythe when she worked; she knew it was a cruel way to say goodbye to life. She preferred to gently uncover the unfortunate soul and carry them in her arms to their new home, a place that, though perfect, no one wanted to go to for fear of forgetting. That night, as she embraced a sweet old man who talked in his sleep, she left her sterile weapon on the floor, unaware of a little grandson whose curiosity got the better of him. When she returned to the house for her tool, there was a tender, cold body weakly clutching the instrument, waiting to be taken back to his grandfather, so that he could tell him stories of the life he never got to have.",
      "Looking at the moon, Death asked whether her work did any good. She sobbed inconsolably, letting her acid tears water the dry mud, praying that from it would be born the little boy she had kept from growing up. She slept surrounded by green grass and, in her dreams, a mirage embraced her; it told her everything would be all right. The Reaper woke surrounded by dead grass; her friend, the moon, had gone. The universe delighted in reminding her of the curse of her being. She rose steeped in helplessness, looked at the pale grass and, in that instant, swore to the wind that no one would ever see her again. She would go far away; she would never hurt anyone again, nothing else would suffer because of her skin.",
      "She began to walk, convinced she would never return. But, among bitter steps and thick sadness, the wind blew hard, forcing her to look at the meadow where she had learned to dream. And it was then that Death saw that, from her tears, a small orange flower was beginning to sprout. Overjoyed, she wanted to approach it, kneel and caress it, and welcome it to the world where the sun would shine on it as much as it possibly could. But, before brushing it, she remembered the curse of her touch and, from a distance, she watched that plant with delight, promising it that she would never cause it pain.",
      "The months passed slowly and, from that young flower, the field did not stop growing. The meadow, which had always been green, was robbed of its essence. Now it was flooded with colors that shone even in the darkest nightfall. Death, terrified of harming the plants, took a step back every time new ones sprouted; she was happy at a distance, knowing that, at last, something of hers did not take joy away from anyone. When half the year had passed, she decided to leave the field; her home was not hers, it belonged to what she would never stop loving.",
      "She went far away, explored the world and never managed to find a flower like the one she had raised. She was happy, exploring, forgetting the work that, though hers, she had never wanted to do. For the first time she saw how people lived. They smiled. No one had the fear she was used to seeing. She decided her absence was a reason for joy and so she kept away from the crowds. Long weeks passed in which she withdrew from everything. And, after hundreds of kilometers, she finally sat down on the shore of an unknown beach to rest. She smiled as she looked at the ocean, remembering how her salty tears had created the miracle her touch could never achieve. She contemplated the horizon for hours; she lost her gaze in the distance, letting herself be rocked by the speech of the sea. Tired, she closed her eyes and dreamed again. She let her mind guide her, but, while she wasn't looking, her clothes grew colder; the waves stopped advancing. It was then that she saw a black storm beginning to form. Death stood up without taking her eyes off the horizon and, in that instant, an icy whisper made itself known.",
      "“I will come for her,” Winter told Death. “You will not be able to stop me.”",
      "The Reaper, terrified, ran back home to protect her flower. When she arrived, she saw a colossal field of flowers brimming with color. Each was of a different height and beauty, so that when the wind blew they looked like waves of unimaginable pigment. Death, without approaching any of them, called out for her creation, but none answered; they knew winter would be guided by her voice. The Reaper tried to help from a distance, but nothing helped them prepare for the beginning of this new season.",
      "In time, winter found the meadow and, with one slow touch, the world that had been created froze. Death watched flowers of intense color fade. She could not accept that this would happen to her daughter and so she broke her promise never to come close, and went in.",
      "The cold grass crunched beneath her steps. The plants were brutally murdered by the frost. Death kept going, but she felt something horrible in her heart. It could not be possible that all this beauty should die in such a horrible way. Where was the warmth of death? The last embrace before saying goodbye? The Reaper realized that everyone kills, but few do it with love. She could not let her daughter die alone in the cold and so she decided to be the one to hold her as she died, so she could whisper tenderly to her of her motherly love. She found her daughter at the center of the meadow, reminding her mother that she had been the heart that gave life to such color. Her mother knelt carefully, but her presence alone was curse enough; as she drew near, the flowers around her lost strength, their petals grew weary and the makeup of each of them ran with fear. Finally, the Reaper covered her little girl with her body, forming a dome that protected her from the hail. All winter long, Death embraced her only daughter. There was not a moment when she moved away. She told her the stories that, though she had wanted to, she had never told; she spoke of her childhood in the meadow and of the gift she never accepted. In time, the winter began to ease. The cold stopped freezing. Death rose carefully, only to see her daughter lying in the sand of that field where nothing would ever again gleam beneath the starlight.",
      "She remained seated, watching the end of the time she had been able to live. All the flowers lost their essence; their petals torn, their stems ripped from the ground by a wind heavy with malice. But among them all there was one that kept its color. She had been able to save her daughter from that unnamable cruel death. With the tenderness of an embrace she had let her daughter rest in peace.",
      "Death stood up and, on her bare feet, began to walk away. She wept, hoping that, in this new grief, her daughter would bloom again. But nothing came back anymore; only the ice thawed, to make way for spring once more.",
    ],
  },
  "7": {
    title: "The Light Is at the Beginning of the Tunnel, Not the End",
    summary: "A tunnel we all walk through, moving away from the light we come from.",
    description:
      "On the long road we all choose as we grow up, those who turn back, and the certainty that, at some point, we will find the light again.",
    epigraph: "To be read with the song “Le tunnel” by Sylvain Chauveau",
    content: [
      "There is a tunnel we all go into. They tell us there is no way out and, even so, it has never really mattered to us. We all walk through it, forgetting the light we come from to explore the unnamed darkness. Some grow tired, decide to turn around and, when they do, we never see them again. In the distance we see their silhouettes, approaching the light we abandoned, but the years go by and, even so, when we briefly turn around, we still see them walking. It is a long road we have chosen, whichever direction we wish to go. But a great adventure awaits us; that is why we walk, for our young eagerness to name things. Our future awaits us, our eyes shine, they guide us as we go. There is desire and strength; we are lucky to have friends to walk with. And though the light moves away from us, we know we come from it, and at some point we will find it again. We can always turn back, but for now our house is far away, and that is why we have accepted the road as our home.",
    ],
  },
  "8": {
    title: "In the Hallway of My House",
    summary: "Every morning, a window at the end of the hallway lets in a few seconds of dawn.",
    description:
      "The dust, the wood and the family portraits regain their color with the first light of day. Every morning he walks towards it, and every morning the sun hides again.",
    content: [
      "At the end of the decaying hallway of my house, there is a window that has managed to keep its youth. From it the sun emerges every morning, and for a few seconds, in a brief instant, the honeyed clarity of day reveals the condition of the corridor. I see the dust sailing through the warm springs of dawn, rocked by imperceptible currents I only felt as I grew up. The furniture regains its essence as it is flooded with light, once again showing the polished color of the seasoned wood it was made from and, in turn, the portraits of my family reflect the golden gleam that springs from the distant horizon. Every morning I walk towards the dawn, ignoring the crunch of glass as I step on the floor, trying to get closer to what is far away and to understand the language in which that golden spring whispers to me. But the imperfection of dawn is that it is not eternal. In a sigh, the graceful warmth fades; the sun hides among the artificial jungles of glass. Every morning I end up at the end of the hallway, consumed by darkness. Watching everything that gleamed go out, looking at the half-open door of my room, remembering the fine brushstroke of morning caressing my face, understanding that no alarm will ever wake me before daybreak, realizing that I will only wake to the touch of the unreachable: the fleeting light of dawn.",
    ],
  },
  "9": {
    title: "The Theater",
    summary: "An entire audience waits in a ruined theater for the return of an old man who vanished behind the curtain.",
    description:
      "One November night, an old man steps onto the stage, confesses his life and disappears behind the curtain. The audience stays waiting for years, while outside the world goes on happening.",
    content: [
      "It crumbled at the mere touch of the wind, and even so, your eyes never stopped watching it. Thousands of stories told between the peeling walls of the theater, delicately expressing the metaphorized condition of humanity. Its revenges, its hatreds; its longing to love. The floors infected with grimy green, the seats corrupted by the absence of people. Shards that were once windows. Ancient carpets bathed in thick dust. Spotlights pointing at the shadows, trying to find in them the artists they were used to illuminating. The actors' altar forgotten behind the curtain of darkness.",
      "You were too young to remember, but one November day the audience vanished. Lost in the applause of the crowd, the actors believed themselves to be the characters of their story. They gazed at the audience and, from the height of their glory, promised the audience that what they had witnessed that night was not a production. They offered the crowd the chance to explore a distant world; and an old man, worn down by time, raised his hand to be the tribute of the new performance. He made his way with slow steps to the center of the theater and, once the burning spotlights stung his pupils, the audience applauded. The man, exposed to everyone, was asked about his life, and as he timidly clutched his worn jacket, trying to find refuge in it, he answered. He said that since childhood he had found no joy, that while he waited for his death, he came to the theater to distract himself watching the lives that, though he had wanted to, he never lived.",
      "His voice echoed through the old theater, infecting the hearts of the crowd with a thick sadness. Long seconds devoured the happiness the previous act had cultivated; reality crept back in among the cold seats, reminding everyone of the frozen world that awaited them once they escaped the velvet walls that protected them from winter. Everyone, silent, watched the man step into the great wall of fabric that separated fantasy from reality, watching his body be consumed by the supple curtain brimming with scarlet essence. Unanimously, the audience reflected on the old man's existence, on the abyss his words had uttered, on the loneliness he had come to accept. A life worn away by the friction the shadows had exerted on his dreams. In the last stage of his adulthood, he decided to disappear before everyone to the other side of the theater, to see from a stage, with his tired eyes, the people he had never greeted for shame of being judged. His last look, directed at an audience of strangers, was a plea for forgiveness.",
      "-oo0oo-",
      "Sheltered in the absorbing magic of the theater, no one thought of the world beyond the glass. But that night, the grass froze. The night sky shone with faint strength; the naked stars formed a new constellation. A white fox, walking through the withered wheat, found a tree without bark, wounded by the hail. It rested at the foot of its hollowed roots and, feeling the touch of its drooping branches, realized that, by chance, it had found the tree where its mother had raised it. It went into the frozen shell of its old life: a lifeless trunk, haunted by a soul that longed to rise again. It sank into it, and the warmth of its fur gave it new strength. Trapped in the claws of winter, the tree blossomed. But, consumed by the spell of an empty curtain, no one in the theater saw it. The wait for the old man became the essence of the act. Hours dwindled into minutes. The world stood still. Everyone, from their seats, gazed at an uninhabited stage, eagerly awaiting a new story.",
      "But long years went by. The wrinkles deepened, the eyelids began to grow heavy, and the last look of many was directed at the emptiness their expectations had been able to create. In time, the sumptuous walls deteriorated. The hands of the clocks grew slack, slowing their pace. The building that had been a symbol of hope ended up corroded by the years. Its roof finally collapsed. And among the rubble of wood and fabric, there remained a single person who, still from his seat, admired the night. From the ruins he contemplated the stars, letting the constellations tell him stories of the beyond. Weeks went by. During the day he watched the empty act, and at night, the starry sky. The spring solstice arrived, bringing with it, on its first night, a fierce aurora borealis. He watched its blazing colors light up the sky, its brushstrokes on the black astral abyss.",
      "The man lost his senses amid so much beauty. He could not conceive that the world could express itself with such intensity. There was a universe out there, and he himself had shut himself off from such loveliness. With trembling strength he managed to rise from the dusty seat. And, in his intermittent madness, he decided to move forward. He walked among the remains of the only building that had been able to speak, remembering the stories that had always inspired him to imagine since he was a child. It was now, as an adult, at the doors of the theater, that he understood his illness. His mistake, like the old man's, had been to wait. His lips were no different from the actors'. His too could tell stories.",
      "He looked one last time at the fallen curtain, where the old man had managed to escape, and his hand pushed the door, taking him into the world on which all stories are based. As he left the theater, spring awaited him with ardor. But, among all the trees, only one remained frozen, awaiting the warmth of winter so that its leaves could sprout.",
    ],
  },
  "10": {
    title: "Goldie",
    summary: "Every night a boy plays on the beach, trying to make the Moon cry with his music.",
    description:
      "While his parents sleep, a boy slips away to the shore to play for the Moon. Without knowing it, his song awakens the memories and dreams of an entire coastal town.",
    content: [
      "On this warm summer night, musical notes sail across the ocean until they are lost at sea. A boy of great skill plays his instrument, trying to see whether his melody can make the Moon cry. His fingers gently caress the strings, which, after so many days, he already knows how to make sing. His eyes, lost in the starry abyss that is the sky, convinced all by himself that he can only measure in tears the quality of the art he has managed to create. The calm night breeze blends with the rhythm of the waves. The sand scattered by the gentle touch of the wind travels like a faint mist barely centimeters above the ground, reaching deep into the shy town, where sleepless old men, from high on their balconies, drink without their families ever waking.",
      "It is always in the depths of the night that the kid decides to escape; his parents bolt the door of the room where they sleep, and when he hears the metallic noise coming from the hallway he knows he can go. He slips out through his window and, after a short jump, the damp grass touches his small feet. Under the light of the stars, he walks along the white sand beach, watching, as he goes, how the shadows that live beneath the palm trees, swayed by the wind, begin to wave at him.",
      "Every night, on the shore of the town, the inlet of the sea, the night evokes his song. And without knowing it, while he focuses only on the Moon, the world begins to change. In the town, the thin fabric curtains are stirred, not by the breeze, but by his playing. The warm streetlights bloom with their faint glow, lighting up the narrow streets where the cats, hearing the melody, curl up to rest. Children who don't sleep, without closing their eyes, begin to dream; those old men who drink are reminded of the memory they wanted to forget. A small coastal town that only shines in the dark. A lighthouse flashes intermittently in the distance, fitfully lighting the rooms where mothers without children can at last find rest.",
      "Strangers united by a boy; everyone knows the reason for his song. And, though it is a sad one, it is when they hear it in the small hours that the townspeople find inspiration. The boy does not know the effect of his song; he only looks at the Moon, which answers him with indifference. But, if he looked at the stars, he would see that it is they who, understanding his story, are crying, creating a rain across the galaxy that everyone, astonished, cannot stop watching.",
      "There will come a day when the Moon will no longer be his muse. And that day, however far away, will come.",
    ],
  },
  "11": {
    title: "Don’t ever change",
    summary: "In a meadow flooded by storms, a man asks a machine never to change.",
    description:
      "Everything around him transforms, sinks into the mud or disappears with time. Only the constant noise of a metal machine offers him the one certainty he has left.",
    content: [
      "His soul levitated with the relief of its voice: its perfect uniformity, its predictable function. The mud eagerly consumed his worn-out shoes. The grass, greener than ever from the rain of the unpredictable storms, was scattered without harmony over that damp earth. Earthworms made their way through the slippery ground, eroded by the world's constant need to transform itself with time. The sky, patched by an inconstant gray stain, kept shifting color, revealing before his eyes an endless, illuminated wetland, only to cover it again. Trees in the distance poured streams from their deciduous leaves. The transient light of the sky lit the meadow in slow gusts, giving the calm sensation of time slowing down. The wind rippled the nearly drowned grass, whistling an inconsistent melody.",
      "Among the howls of the breeze, he heard its silvery voice: its constant machining, cold gears rubbing against one another without pause, creating a single sound that inconsistent nature could never recreate. A cadenced melody of industrial percussion, shattering the unpredictable songs and silences of nature. Without coming closer, he could feel the inhuman touch of the apparatus. Its frigid, ferrous touch, polished until it became the smooth, continuous machinery it is. A metal obelisk designed to last, identical to the day it was made. Not a scratch nor a fault, an immutable genius lost in a field submerged by storms.",
      "A world in constant change, with no guarantee of evolving. Everything ends up sunk by the rain, buried in mud and corroded by an unfeeling naturalness. He watches what was always there begin to slip through his fingers. The guarantee of the machinery: to be the only thing created for a single reason and to carry it out until it disappears. For years, the world has been shaped by the ticking of the minutes. Animals migrating in winter never to return. Fallen trees with no seeds to grow again from. A sky that cannot promise stars even at night. It is a world in motion and he, from his window, watches it astonished, wondering whether it will be the same view when the sun decides to rise.",
      "Today the field is besieged by volatile storms. Uncontrollable bursts of rain that, without any pattern, pour down as hard as they can. The clearings of the plain are deceived, caressed at first by the water until they realize they are beginning to sink. In a world without certainties, he only asks that the machine never stop working. That it be whatever it is, and that its machinery never age. That the vibrant sounds of compressed gas and rhythmic silences last until the meadow is no longer what it is.",
      "“Don't ever change,” he whispered to the only certainty the man could have. He cried simple tears before leaving; the rain did not stop conquering. His weeping camouflaged by the permanent metamorphosis of the storm. Giant puddles made of too much rain and too few tears anchor themselves in the mud to grow. The green grass that first drew him to that remote place can barely be seen.",
    ],
  },
  "12": {
    summary: "On the weight of what was never said, and two souls who find each other again beside a river.",
    description:
      "There is a void that grows for as long as it has no name. A man remembers the night when, at the end of a dark forest, he heard two souls reunite and understood why there are words that must never be left unsaid.",
  },
};
